CREATE TABLE [dbo].[TravelInfo](
	[TravelInfoID] [int] NOT NULL,
	[PositionsID] [int] NULL,
	[JobOrdersID] [int] NULL,
	[CreatedOn] [datetime] NULL,
	[CreatedBy] [nvarchar](20) NULL,
	[UpdatedOn] [datetime] NULL,
	[UpdatedBy] [nvarchar](50) NULL,
	[Flight] [bit] NULL,
	[Lodging] [bit] NULL,
	[RentalCar] [bit] NULL,
	[Mileage] [bit] NULL,
	[Shuttle] [bit] NULL,
	[Comments] [text] NULL,
	[DepartureAirport] [nvarchar](50) NULL,
	[DepartureDate] [datetime] NULL,
	[DepartureFlight] [nvarchar](50) NULL,
	[DepartureComments] [text] NULL,
	[FlightChanges] [nvarchar](255) NULL,
	[ReturnAirport] [nvarchar](50) NULL,
	[ReturnFlight] [nvarchar](50) NULL,
	[ReturnDate] [datetime] NULL,
	[LodgingBilling] [nvarchar](50) NULL,
	[LodgingComments] [text] NULL,
	[LodgingContact] [nvarchar](255) NULL,
	[LodgingConfirmation] [nvarchar](50) NULL,
	[CheckIn] [datetime] NULL,
	[CheckOut] [datetime] NULL,
	[CarBilling] [nvarchar](50) NULL,
	[CarConfirmation] [nvarchar](50) NULL,
	[CarComments] [text] NULL,
	[CarPickup] [datetime] NULL,
	[CarReturn] [datetime] NULL,
	[MileageRate] [money] NULL,
	[MileageComments] [text] NULL,
	[ShuttlePickUp] [datetime] NULL,
	[ShuttleDropOff] [datetime] NULL,
	[ShuttleComments] [text] NULL,
	[ShuttlePickupConfirm] [nvarchar](50) NULL,
	[ShuttleDropConfirm] [nvarchar](50) NULL,
	[TravelDateFrom] [datetime] NULL,
	[TravelDateTo] [datetime] NULL,
	[TravelDescription] [nvarchar](255) NULL,
	[FlightStatus] [nvarchar](50) NULL,
	[LodgingStatus] [nvarchar](50) NULL,
	[RentalCarStatus] [nvarchar](50) NULL,
	[ShuttleStatus] [nvarchar](50) NULL,
	[StintNo] [nvarchar](50) NULL,
	[CarContact] [nvarchar](255) NULL,
	[OthearFuel] [bit] NULL,
	[OthearMileage] [bit] NULL,
	[OthearParking] [bit] NULL,
	[OthearTolls] [bit] NULL,
	[OthearTaxi] [bit] NULL,
	[UTCCreatedOn] [smallint] NULL,
	[UTCUpdatedOn] [smallint] NULL,
	[OthearBaggage] [bit] NULL,
 CONSTRAINT [PK_TravelInfo1] PRIMARY KEY CLUSTERED 
(
	[TravelInfoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

GRANT  SELECT ,  UPDATE ,  INSERT ,  DELETE  ON [dbo].[TravelInfo] TO [DeskFlowUsers]
