ALTER TABLE ProjectsCallStatus DISABLE TRIGGER ProjectsCallStatusUpdateG
UPDATE ProjectsCallStatus set StatusDescription=NULL where StatusDescription=''
ALTER TABLE ProjectsCallStatus ENABLE TRIGGER ProjectsCallStatusUpdateG
